CREATE TABLE `beli` (
  `NOTA` varchar(15) NOT NULL,
  `LOKASI_ID` varchar(6) NOT NULL,
  `SUPPLIER_ID` varchar(10) NOT NULL,
  `STATUS_NOTA` char(1) DEFAULT 'T',
  `STATUS_BAYAR` char(1) DEFAULT 'L',
  `TANGGAL` date DEFAULT NULL,
  `TEMPO` date DEFAULT NULL,
  `DISKON` decimal(10,3) DEFAULT '0.000',
  `PPN` decimal(10,3) DEFAULT '0.000',
  `KETERANGAN` varchar(100) DEFAULT NULL,
  `USER_ADMIN` varchar(15) DEFAULT NULL,
  `URUT` int DEFAULT NULL,
  `OPERATOR` varchar(30) DEFAULT NULL,
  `NOTA_JUAL` varchar(14) DEFAULT NULL,
  `TOTAL_NOTA` decimal(18,3) DEFAULT '0.000',
  `TOTAL_PELUNASAN_NOTA` decimal(18,3) DEFAULT '0.000',
  `PROFIT` decimal(18,3) DEFAULT '0.000',
  `PRINT_COUNTER` int NOT NULL DEFAULT '0'
) ;

ALTER TABLE `beli`
  ADD PRIMARY KEY (`NOTA`),
  ADD KEY `FK_BELI_1` (`LOKASI_ID`),
  ADD KEY `FK_BELI_2` (`SUPPLIER_ID`);

