CREATE TABLE `pelunasan_hutang` (
  `NO_PELUNASAN` varchar(15) NOT NULL,
  `SUPPLIER_ID` varchar(10) NOT NULL,
  `TANGGAL` date DEFAULT NULL,
  `KETERANGAN` varchar(256) DEFAULT NULL,
  `URUT` int DEFAULT NULL,
  `OPERATOR` varchar(30) DEFAULT NULL,
  `PRINT_COUNTER` int NOT NULL DEFAULT '0'
) ;


ALTER TABLE `pelunasan_hutang`
  ADD PRIMARY KEY (`NO_PELUNASAN`),
  ADD KEY `FK_PELUNASAN_HUTANG_1` (`SUPPLIER_ID`);
COMMIT;


