
CREATE TABLE `supplier` (
  `KODE` varchar(10) NOT NULL,
  `NAMA` varchar(30) DEFAULT NULL,
  `ALAMAT` varchar(50) DEFAULT NULL,
  `KONTAK` varchar(30) DEFAULT NULL,
  `NPWP` varchar(25) DEFAULT NULL,
  `JATUH_TEMPO` smallint DEFAULT NULL,
  `URUT` smallint DEFAULT NULL,
  `WILAYAH_ID` varchar(5) NOT NULL,
  `DEF` smallint DEFAULT '0',
  `ALAMAT2` varchar(50) DEFAULT NULL,
  `KODE_BARCODE` varchar(10) DEFAULT NULL,
  `PLAFON_HUTANG` int DEFAULT '0',
  `TOTAL_HUTANG` decimal(18,2) DEFAULT '0.00',
  `TOTAL_PELUNASAN_HUTANG` decimal(18,2) DEFAULT '0.00',
  `TELEPON` varchar(20) DEFAULT NULL
) 


ALTER TABLE `supplier`
  ADD PRIMARY KEY (`KODE`);

