
CREATE TABLE `user_admin` (
  `NAMA` varchar(15) NOT NULL,
  `PASS` varchar(256) DEFAULT NULL,
  `IS_AKTIF` smallint DEFAULT '1',
  `GROUP_HAK_AKSES_ID` int NOT NULL,
  `ALAMAT` varchar(50) DEFAULT NULL,
  `WILAYAH_ID` varchar(5) DEFAULT NULL,
  `TELEPON` varchar(25) DEFAULT NULL,
  `NO_REKENING` varchar(30) DEFAULT NULL,
  `GAJI_POKOK` int DEFAULT '0',
  `IS_SHOW_INFO_HUTANG_PIUTANG` smallint DEFAULT '0',
  `IS_SHOW_PROFIT` smallint DEFAULT '0',
  `IS_ALLOW_UPDATE_PLAFON` smallint DEFAULT '0'
); 

ALTER TABLE `user_admin`
  ADD PRIMARY KEY (`NAMA`),

ALTER TABLE `user_admin`,
  ADD CONSTRAINT `FK_USER_ADMIN` FOREIGN KEY (`WILAYAH_ID`) REFERENCES `wilayah` (`KODE`) ON DELETE CASCADE ON UPDATE CASCADE,
